name: Website Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check Website Health
      run: |
        STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://siaflow.lovable.app/)
        if [ "$STATUS" != "200" ]; then
          echo "Website is down!"
          exit 1
        fi
